### ISSUE TITLE
Add support for ENV based auth fallback

### ISSUE THREAD

**Issue by juhamust** [marcincuber/aws-cfm-utils#16]
To support easy deployments from local (usually `.aws/credentials`) and CI environments (usually environment variables), fallback to environment based authentication when profile cannot be found. Then `--profile` can be hardcoded in commands and it still works in CI env.

**Comment by juhamust** [comment]
Apparently the `AWS_PROFILE` works, making it easy to set it locally, when needed.

**Comment by marcincuber** [comment]
part of v1.6.6
