### ISSUE TITLE
Capabilities options does not accept CAPABILITY_AUTO_EXPAND

### ISSUE THREAD

**Issue by juhamust** [marcincuber/aws-cfm-utils#20]
As stated in title, --capabilities option does not accept CAPABILITY_AUTO_EXPAND needed with AWS SAM (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-deploying.html) deployments.

**Comment by marcincuber** [comment]
Thanks for the PR. 
Newly released version includes this. [aws-cfm-utils v1.6.7](https://www.npmjs.com/package/aws-cfm-utils/v/1.6.7)

**Comment by juhamust** [comment]
Thanks for the quick merge and release! 👍
