### ISSUE TITLE
Deploy template

### ISSUE THREAD

**Issue by obazoud** [marcincuber/aws-cfm-utils#27]
Could you please add options to deploy template like this (instead of `create-stack / update-stack)
- `aws cloudformation package`
- show change sets `aws cloudformation deploy --no-execute-changeset`
- `aws cloudformation deploy`

**Comment by marcincuber** [comment]
I am not too clear what you would like to be implemented. Could you give more details here with descriptive example?

**Comment by marcincuber** [comment]
Looks like there is no way to do it with aws-sdk. Closing for now.
